import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/theme/app_colors.dart';
import '../../../data/models/budget_model.dart';
import '../../../data/models/user_model.dart';
import '../../providers/auth_provider.dart';
import '../../providers/budget_provider.dart';
import '../../providers/household_provider.dart'
    show currentUserHouseholdProvider, householdMemberDetailsProvider, HouseholdMemberDetail;

/*
MANUAL TEST CHECKLIST — ADD BUDGET
1) Head creates family or member budget for a month; member budgets show real names (“My”, “Khoi”), never “Unknown member”.
2) Member user cannot create a budget (button disabled/blocked); attempting shows a friendly message.
3) Member view after creation shows only their budgets plus family budgets; no other members leak.
4) Shared expense ($20) from household_shared wallet increments member usage; personal wallet does not; edit to $50 then delete resets to $0.
5) Rules enforced: member cannot create/update/delete budgets or read other members’ budget docs/usages; head can read all; no infinite loading on permission denied (Retry works).
*/

class AddBudgetScreen extends ConsumerStatefulWidget {
  const AddBudgetScreen({super.key});

  @override
  ConsumerState<AddBudgetScreen> createState() => _AddBudgetScreenState();
}

class _AddBudgetScreenState extends ConsumerState<AddBudgetScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _amountController = TextEditingController();
  final _alertThresholdController = TextEditingController(text: '80');

  String? _selectedMemberUserId;
  String? _selectedMemberName;
  bool _isMemberBudget = false;
  bool _isLoading = false;
  DateTime _selectedMonth = DateTime.now();

  @override
  void dispose() {
    _nameController.dispose();
    _amountController.dispose();
    _alertThresholdController.dispose();
    super.dispose();
  }

  Future<void> _saveBudget() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = ref.read(authUserProvider).value;
      final household = ref.read(currentUserHouseholdProvider).valueOrNull;

      if (user == null) {
        throw Exception('User not logged in');
      }
      if (!user.isHead) {
        throw Exception('Only heads can create budgets');
      }
      if (household == null) {
        throw Exception('Household required for budgets');
      }

      // Monthly period key
      final startDate = DateTime(_selectedMonth.year, _selectedMonth.month, 1);
      final endDate = DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0, 23, 59, 59);
      final periodKey =
          '${_selectedMonth.year.toString().padLeft(4, '0')}-${_selectedMonth.month.toString().padLeft(2, '0')}';

      if (_isMemberBudget && (_selectedMemberUserId == null || _selectedMemberUserId!.isEmpty)) {
        throw Exception('Select a member for member budget');
      }

      final budget = BudgetModel(
        budgetId: '', // Will be generated by Firestore
        categoryId: '',
        amount: double.parse(_amountController.text),
        startDate: startDate,
        endDate: endDate,
        userId: null,
        householdId: household.householdId,
        alertThreshold: (double.tryParse(_alertThresholdController.text) ?? 80) / 100,
        budgetType: _isMemberBudget ? 'member' : 'family',
        memberUserId: _isMemberBudget ? _selectedMemberUserId : null,
        memberDisplayName: _isMemberBudget ? _selectedMemberName?.trim() : null,
        periodKey: periodKey,
        createdBy: user.userId,
        createdAt: DateTime.now(),
        walletScopeFilter: 'household_shared',
      );

      final budgetId = await ref.read(budgetNotifierProvider.notifier).createBudget(budget);

      if (budgetId != null && mounted) {
        debugPrint(
            '[BUDGET_CREATE] success id=$budgetId period=$periodKey type=${budget.budgetType} household=${household.householdId} member=${budget.memberUserId ?? 'null'}');
        if (_isMemberBudget) {
          debugPrint('[BUDGET_CREATE] member_budget uid=${budget.memberUserId} name=${budget.memberDisplayName}');
        }

        // Refresh budgets list for this household/period
        // CRITICAL: Must match exact params used in budget_list_screen
        ref.invalidate(
          activeBudgetsWithUsageProvider(
            BudgetParams(
              userId: null, // household budgets don't filter by userId
              householdId: household.householdId,
              periodKey: periodKey,
              isHead: user.isHead,
              viewerUserId: user.userId,
            ),
          ),
        );

        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Budget created successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating budget: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authUserProvider);
    final UserModel? user = authState.value;
    final householdAsync = ref.watch(currentUserHouseholdProvider);
    final householdId = householdAsync.valueOrNull?.householdId ?? '';
    final canCreate = user?.isHead ?? false;
    final memberDetailsAsync = householdId.isNotEmpty
        ? ref.watch(householdMemberDetailsProvider(householdId))
        : const AsyncValue.data(<HouseholdMemberDetail>[]);

    // Default name suggestions
    final monthLabel =
        '${_selectedMonth.year}-${_selectedMonth.month.toString().padLeft(2, '0')}';
    if (_nameController.text.isEmpty) {
      _nameController.text =
          _isMemberBudget && _selectedMemberUserId != null && _selectedMemberUserId!.isNotEmpty
              ? 'Member Budget - $monthLabel'
              : 'Family Budget - $monthLabel';
    }

    return Scaffold(
      backgroundColor: AppColors.backgroundLight,
      appBar: AppBar(
        title: const Text('Create Budget'),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                if (!canCreate)
                  Card(
                    color: AppColors.primary.withOpacity(0.08),
                    child: const ListTile(
                      leading: Icon(Icons.info_outline),
                      title: Text('Only heads can create budgets.'),
                      subtitle: Text('You can still view budgets from Home.'),
                    ),
                  ),
                const SizedBox(height: 8),

                // Budget Name
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    labelText: 'Budget Name',
                    hintText: 'e.g., Monthly Groceries',
                    prefixIcon: Icon(Icons.label),
                  ),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter a budget name';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                // Amount
                TextFormField(
                  controller: _amountController,
                  decoration: const InputDecoration(
                    labelText: 'Budget Amount',
                    hintText: '0.00',
                    prefixText: '\$ ',
                    prefixIcon: Icon(Icons.attach_money),
                  ),
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter an amount';
                    }
                    if (double.tryParse(value) == null) {
                      return 'Please enter a valid number';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                // Month selector (YYYY-MM)
                ListTile(
                  leading: const Icon(Icons.calendar_today),
                  title: const Text('Budget month'),
                  subtitle: Text(
                    '${_selectedMonth.year}-${_selectedMonth.month.toString().padLeft(2, '0')}',
                  ),
                  onTap: () async {
                    final picked = await showDatePicker(
                      context: context,
                      initialDate: _selectedMonth,
                      firstDate: DateTime(DateTime.now().year - 1, 1, 1),
                      lastDate: DateTime(DateTime.now().year + 1, 12, 31),
                      initialEntryMode: DatePickerEntryMode.calendarOnly,
                    );
                    if (picked != null) {
                      setState(() => _selectedMonth = picked);
                    }
                  },
                ),
                const SizedBox(height: 16),

                SwitchListTile(
                  title: const Text('Member budget'),
                  subtitle: const Text('Count spending of one member only'),
                  value: _isMemberBudget,
                  onChanged: (val) {
                    setState(() {
                      _isMemberBudget = val;
                      if (!val) {
                        _selectedMemberUserId = null;
                        _selectedMemberName = null;
                      }
                    });
                  },
                ),
                if (_isMemberBudget) ...[
                  const SizedBox(height: 8),
                  memberDetailsAsync.when(
                    data: (members) {
                      debugPrint(
                          '[HOUSEHOLD_MEMBERS] Loaded ${members.length} members for household=$householdId');
                      if (members.isEmpty) {
                        return const Text('No household members found.');
                      }
                      return DropdownButtonFormField<String>(
                        value: _selectedMemberUserId,
                        decoration: const InputDecoration(
                          labelText: 'Select member',
                          prefixIcon: Icon(Icons.person),
                        ),
                        items: members
                            .map(
                              (m) => DropdownMenuItem<String>(
                                value: m.membership.userId,
                                child: Text(m.displayName),
                              ),
                            )
                            .toList(),
                        onChanged: (val) {
                          setState(() {
                            _selectedMemberUserId = val;
                            _selectedMemberName = _memberName(members, val ?? '');
                            _nameController.text =
                                '${_memberName(members, val ?? '')} Budget - $monthLabel';
                          });
                        },
                        validator: (value) {
                          if (_isMemberBudget && (value == null || value.isEmpty)) {
                            return 'Select a member';
                          }
                          return null;
                        },
                      );
                    },
                    loading: () => const LinearProgressIndicator(),
                    error: (e, _) => Text('Unable to load members: $e'),
                  ),
                  const SizedBox(height: 16),
                ],

                // Alert Threshold
                TextFormField(
                  controller: _alertThresholdController,
                  decoration: const InputDecoration(
                    labelText: 'Alert Threshold (%)',
                    hintText: '80',
                    prefixIcon: Icon(Icons.notifications),
                    suffixText: '%',
                  ),
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value != null && value.isNotEmpty) {
                      final threshold = double.tryParse(value);
                      if (threshold == null || threshold < 0 || threshold > 100) {
                        return 'Please enter a value between 0 and 100';
                      }
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                const SizedBox(height: 32),

                // Save Button
                ElevatedButton(
                  onPressed: _isLoading || !canCreate ? null : _saveBudget,
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Text('Create Budget'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  String _memberName(List<HouseholdMemberDetail> members, String userId) {
    final match = members.where((m) => m.membership.userId == userId);
    if (match.isEmpty) return 'Member';
    return match.first.displayName;
  }
}
